### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'RwLock reader count overflow' on Zeitgeist Collator Version: 0.3.4-893344f-x86_64-linux-gnu

### ISSUE THREAD

**Issue by m-saxemberg** [zeitgeistpm/zeitgeist#709]
The following message was found on a collator node with the following characteristics. 
Specs:
64GB RAM NVMe storage
Parameters:
"zeitgeist --chain=zeitgeist --collator --state-cache-size 0 --pruning=archive -- --state-cache-size 0 --unsafe-pruning --pruning 1000" 

>2022-07-15 16:05:47 [__ Zeitgeist Parachain] __ Idle (33 peers), best: #914592 (
>0x094f_0ebe), finalized #914590 (0x843d_9ac3), _ 0.9kiB/s _ 1.2kiB/s  
> 2022-07-15 16:05:47 [Relaychain] __ Idle (38 peers), best: #13572033 (0x0da6_aeb
> 8), finalized #13572029 (0xf61d_25c2), _ 635.2kiB/s _ 671.8kiB/s  
> 
> ====================                                                                                
> Version: 0.3.4-893344f-x86_64-linux-gnu       
>                                 
>    0: sp_panic_handler::set::{{closure}} 
>    1: std::panicking::rust_panic_with_hook at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:702:17                      
>    2: std::panicking::begin_panic_handler::{{closure}} at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/p
> anicking.rs:588:13                                                              
>    3: std::sys_common::backtrace::__rust_end_short_backtrace at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:138:18                                                
>    4: rust_begin_unwind at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:584:5                                                               
>    5: core::panicking::panic_fmt at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/ panicking.rs:142:14   
>    6: core::panicking::panic_display at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/panicking.rs:72:5
>    7: core::panicking::panic_str at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/panicking.rs:56:5
>    8: core::option::expect_failed at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/option.rs:1855:5                        
>    9: parking_lot::raw_rwlock::RawRwLock::lock_shared_slow
>   10: tracing_subscriber::filter::env::EnvFilter::cares_about_span
>   11: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscrber::Subscriber>::exit
>   12: std::thread::local::LocalKey<T>::with                                       
>   13: tokio::park::thread::CachedParkThread::block_on 
>   14: tokio::runtime::handle::Handle::block_on
>   15: tokio::runtime::task::core::CoreStage<T>::poll
>   16: tokio::runtime::task::harness::Harness<T,S>::poll
>   17: tokio::runtime::blocking::pool::Inner::run
>   18: std::sys_common::backtrace::__rust_begin_short_backtrace
>   19: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/alloc/src/boxed.rs:1866:9 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/alloc/src/boxed.rs:1866:9 std::sys::unix::thread::Thread::new::thread_start at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys/unix/thread.rs:108:17
>   21: start_thread
>   22: clone
> 
> 
> Thread 'tokio-runtime-worker' panicked at 'RwLock reader count overflow', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.2/src/raw_rwlock.rs:698
> 
> This is a bug. Please report it at:
> 
>         https://github.com/zeitgeistpm/zeitgeist/issues
> 
> 

Zeitgeist parachain db available upon request.

**Comment by m-saxemberg** [comment]
After purging the the zeitgeist parachain database, it gave a different error

>====================                                                                
                                                                                    
>Version: 0.3.4-893344f-x86_64-linux-gnu                                                                                                                                  
                                                                                    
>   0: sp_panic_handler::set::{{closure}}                                                                                                                                 
>   1: std::panicking::rust_panic_with_hook  at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:702:17      
>   2: std::panicking::begin_panic_handler::{{closure}} at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:586:13
>   3: std::sys_common::backtrace::__rust_end_short_backtrace at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:138:18
>   4: rust_begin_unwind at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:584:5
>   5: core::panicking::panic_fmt at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/panicking.rs:142:14
>   6: core::panicking::panic at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/panicking.rs:48:5
>   7: <futures_util::future::future::shared::Shared<Fut> as core::future::future::Future>::poll
>   8: <exit_future::Exit as core::future::future::Future>::poll
>   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>  10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
>  11: tokio::runtime::task::core::CoreStage<T>::poll
>  12: tokio::runtime::task::harness::poll_future
>  13: tokio::runtime::task::harness::Harness<T,S>::poll
>  14: std::thread::local::LocalKey<T>::with
>  15: tokio::runtime::thread_pool::worker::Context::run_task
>  16: tokio::runtime::thread_pool::worker::Context::run
>  17: tokio::macros::scoped_tls::ScopedKey<T>::set
>  18: tokio::runtime::thread_pool::worker::run
>  19: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
>  20: tokio::runtime::task::core::CoreStage<T>::poll
>  21: tokio::runtime::task::harness::Harness<T,S>::poll
>  22: tokio::runtime::blocking::pool::Inner::run
>  23: std::sys_common::backtrace::__rust_begin_short_backtrace
>  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
>  25: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/alloc/src/boxed.rs:1866:9  <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/alloc/src/boxed.rs:1866:9      std::sys::unix::thread::Thread::new::thread_start  at rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys/unix/thread.rs:108:17
>  26: start_thread
>  27: clone


>  Thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/shared.rs:296

>  This is a bug. Please report it at:

>        https://github.com/zeitgeistpm/zeitgeist/issues

**Comment by m-saxemberg** [comment]
upon closer inspection, the hardware (CPU) was faulty, the CPU was replaced and now that error has disappeared.
